# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/Documents/FPGA-Miner/xilinx-study/pci-e/pg195-4/xdma_0_ex/imports/xilinx_xdma_pcie_x0y0.xdc

# XDC: D:/Documents/FPGA-Miner/xilinx-study/pci-e/pg195-4/xdma_0_ex/xdma_0_ex.srcs/k410tFM2Constraints.xdc

# IP: ip/xdma_0/xdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_0 || ORIG_REF_NAME==xdma_0} -quiet] -quiet
