# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pci-e/pg195-2/xdma_0_ex/imports/xilinx_xdma_pcie_x0y0.xdc

# XDC: imports/pci-e/FMx-PG195-PCIe-DMA/xdma_0_ex.srcs/constrs_1/new/k410tFM2Constraints.xdc

# IP: ip/xdma_0/xdma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_0 || ORIG_REF_NAME==xdma_0} -quiet] -quiet
